/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.restaurantepresentacion;

import itson.restaurantedominio.ClienteFrecuente;
import itson.restaurantedtos.ClienteFrecuenteActualizadoDTO;
import itson.restaurantedtos.ClienteFrecuenteDTO;
import itson.restaurantenegocio.ClientesFrecuentesBO;
import itson.restaurantenegocio.IClientesFrecuentesBO;
import itson.restaurantenegocio.NegocioException;
import itson.restauranteutil.EncriptadorTelefono;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrea Lara, Nahomi Figueroa, Zaira Barajas
 */
public class ActualizarClientesFORM extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(ActualizarClientesFORM.class.getName());

    private IClientesFrecuentesBO clientesBO;
    ClienteFrecuenteDTO clienteAEditar;
    ClienteFrecuente clienteListo;

    /**
     * Creates new form ActualizarClientes
     */
    public ActualizarClientesFORM(ClienteFrecuenteDTO clienteAEditar) {
        initComponents();
        this.clientesBO = new ClientesFrecuentesBO();
        this.clienteAEditar = clienteAEditar;
        llenarCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlActualizar = new javax.swing.JPanel();
        pnlFormularioActualizar = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo1 = new javax.swing.JLabel();
        lblEjemplo1 = new javax.swing.JLabel();
        lblEjemplo2 = new javax.swing.JLabel();
        lblEjemploCorreo = new javax.swing.JLabel();
        lblEjemploTelefono1 = new javax.swing.JLabel();
        lblEjemploTelefono2 = new javax.swing.JLabel();
        lblEjemploNota = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Cliente Frecuente");

        pnlActualizar.setBackground(new java.awt.Color(255, 255, 255));

        pnlFormularioActualizar.setBackground(new java.awt.Color(254, 178, 26));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNombre.setBackground(new java.awt.Color(254, 178, 26));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(19, 70, 134));
        lblNombre.setText("Nombre(s):");

        lblApellidoP.setBackground(new java.awt.Color(254, 178, 26));
        lblApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblApellidoP.setForeground(new java.awt.Color(19, 70, 134));
        lblApellidoP.setText("Apellido Paterno:");

        lblApellidoM.setBackground(new java.awt.Color(254, 178, 26));
        lblApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblApellidoM.setForeground(new java.awt.Color(19, 70, 134));
        lblApellidoM.setText("Apellido Materno:");

        lblTelefono.setBackground(new java.awt.Color(254, 178, 26));
        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(19, 70, 134));
        lblTelefono.setText("Teléfono:");

        lblCorreo1.setBackground(new java.awt.Color(254, 178, 26));
        lblCorreo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(19, 70, 134));
        lblCorreo1.setText("Correo:");

        lblEjemplo1.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemplo1.setText("Ejemplo:");

        lblEjemplo2.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemplo2.setText("Ejemplo:");

        lblEjemploCorreo.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemploCorreo.setText("micorreo@dominio.com");

        lblEjemploTelefono1.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemploTelefono1.setText("+52-6441-12-12-12");

        lblEjemploTelefono2.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemploTelefono2.setText("+52 6442676767");

        lblEjemploNota.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lblEjemploNota.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemploNota.setText("La lada y guiones son opcionales");

        javax.swing.GroupLayout pnlFormularioActualizarLayout = new javax.swing.GroupLayout(pnlFormularioActualizar);
        pnlFormularioActualizar.setLayout(pnlFormularioActualizarLayout);
        pnlFormularioActualizarLayout.setHorizontalGroup(
            pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioActualizarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioActualizarLayout.createSequentialGroup()
                        .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEjemplo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlFormularioActualizarLayout.createSequentialGroup()
                        .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEjemploTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEjemploTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addComponent(lblEjemploNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioActualizarLayout.createSequentialGroup()
                        .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEjemplo2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEjemploCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        pnlFormularioActualizarLayout.setVerticalGroup(
            pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioActualizarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidoP)
                    .addComponent(lblApellidoM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(lblCorreo1))
                .addGap(14, 14, 14)
                .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlFormularioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioActualizarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEjemplo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEjemploTelefono1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEjemploTelefono2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEjemploNota))
                    .addGroup(pnlFormularioActualizarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblEjemplo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEjemploCorreo)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnActualizar.setBackground(new java.awt.Color(19, 70, 134));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(237, 63, 39));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(19, 70, 134));
        lblTitulo.setText("Actualizar Cliente ");

        javax.swing.GroupLayout pnlActualizarLayout = new javax.swing.GroupLayout(pnlActualizar);
        pnlActualizar.setLayout(pnlActualizarLayout);
        pnlActualizarLayout.setHorizontalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                        .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlFormularioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRegresar)
                                .addGap(123, 123, 123)
                                .addComponent(btnActualizar)
                                .addGap(214, 214, 214)))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(305, 305, 305))))
        );
        pnlActualizarLayout.setVerticalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFormularioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnRegresar))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este botón cierra la ventana, ya que esta es una ventana emergente, lo
     * que permite regresar a la pantalla anterior (ClientesFrecuentesFORM)
     *
     * @param evt hacer click en el botón regresar
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * Este botón utiliza el método actualizarCliente después de confirmar que
     * de verdad se desean aplicar los cambios, para despúes regresar al
     * ClienteFrecuente y cerrar la ventana.
     *
     * @param evt hacer click en el botón actualizar.
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea aplicar los cambios?", "Actualizar Cliente", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            this.clienteListo = actualizarCliente();
            if (clienteListo != null) {
                JOptionPane.showMessageDialog(null, "Se aplicaron los cambios.");
                this.dispose();
            }
        } else {
            this.clienteListo = null;
            JOptionPane.showMessageDialog(null, "No fueron aplicados los cambios.");
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * Getter para el cliente frecuente ya actualizado
     *
     * @return objeto tipo ClienteFrecuente con los datos actualizados
     */
    public ClienteFrecuente getClienteActualizado() {
        return this.clienteListo;
    }

    /**
     * Método para llenar los campos del formulario con los datos del cliente.
     */
    public void llenarCampos() {
        this.txtNombre.setText(clienteAEditar.getNombre());
        this.txtApellidoP.setText(clienteAEditar.getApellidoP());
        this.txtApellidoM.setText(clienteAEditar.getApellidoM());

        try {
            String telefonoPlano = EncriptadorTelefono.desencriptar(clienteAEditar.getNumeroTelefono());
            this.txtTelefono.setText(telefonoPlano);
        } catch (Exception ex) {
            LOGGER.severe("Error al desencriptar teléfono: " + ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No fue posible recuperar el número de teléfono.\nDetalle: " + ex.getMessage(),
                    "Error de desencriptación",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            this.txtTelefono.setText(""); 
        }

        this.txtCorreo.setText(clienteAEditar.getCorreo());
    }

    /**
     * Este método toma todos los datos del formulario para actualizar clientes
     * y los convierte a un DTO para intentar actualizar al cliente
     * correspondiente en la base de datos.
     *
     * @return un objeto tipo ClienteFrecuente
     */
    public ClienteFrecuente actualizarCliente() {
        String nombre;
        String apellidoP;
        String apellidoM;
        String telefono;
        String correo;

        if (!txtNombre.getText().trim().isBlank() || !txtNombre.getText().trim().isEmpty()) {
            nombre = txtNombre.getText();
        } else {
            nombre = null;
        }

        if (!txtApellidoP.getText().trim().isBlank() || !txtApellidoP.getText().trim().isEmpty()) {
            apellidoP = txtApellidoP.getText();
        } else {
            apellidoP = null;
        }

        if (!txtApellidoM.getText().trim().isBlank() || !txtApellidoM.getText().trim().isEmpty()) {
            apellidoM = txtApellidoM.getText();
        } else {
            apellidoM = null;
        }

        if (!txtTelefono.getText().trim().isBlank() || !txtTelefono.getText().trim().isEmpty()) {
            telefono = txtTelefono.getText();
        } else {
            telefono = null;
        }

        if (!txtCorreo.getText().trim().isBlank() || !txtCorreo.getText().trim().isEmpty()) {
            correo = txtCorreo.getText();
        } else {
            correo = null;
        }

        ClienteFrecuenteActualizadoDTO clienteActualizado = new ClienteFrecuenteActualizadoDTO(this.clienteAEditar.getId(), nombre, apellidoP, apellidoM, telefono, correo);

        try {
            return clientesBO.actualizarCliente(clienteActualizado);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar cliente" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblEjemplo1;
    private javax.swing.JLabel lblEjemplo2;
    private javax.swing.JLabel lblEjemploCorreo;
    private javax.swing.JLabel lblEjemploNota;
    private javax.swing.JLabel lblEjemploTelefono1;
    private javax.swing.JLabel lblEjemploTelefono2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlActualizar;
    private javax.swing.JPanel pnlFormularioActualizar;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
