/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.restaurantepresentacion;

import itson.restaurantedtos.IngredienteActualizadoDTO;
import itson.restaurantedtos.ProductoDTO;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nahomi Figueroa
 */
public class ActualizarProductoFORM extends javax.swing.JFrame {

    private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(ActualizarProductoFORM.class.getName());
    private byte[] imagenBytes = null;
    private IngredienteActualizadoDTO ingredienteSeleccionado = null;
    private DefaultTableModel modeloTabla;
    private Long idProductoActual;
    private ProductosControl control;

    /**
     * Creates new form ActualizarProductoFORM
     */
    public ActualizarProductoFORM(Long idProducto) {
        this.idProductoActual = idProducto;
        this.control = new ProductosControl();
        initComponents();
        this.setLocationRelativeTo(null);
        modeloTabla = (DefaultTableModel) jTable1.getModel();
        lblIngredienteencontrado.setText("Ningún ingrediente seleccionado");
        txtCantidad.setText("");

        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int fila = jTable1.rowAtPoint(evt.getPoint());
                int columna = jTable1.columnAtPoint(evt.getPoint());
                if (fila >= 0 && columna == 4) {
                    int confirmacion = JOptionPane.showConfirmDialog(null,
                            "¿Quitar este ingrediente?", "Confirmar", JOptionPane.YES_NO_OPTION);

                    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                        modeloTabla.removeRow(fila);
                    }
                }
            }
        });
        cargarDatosProducto();
    }

    /**
     * Método para cargar los datos del producto a editar en los campos del
     * formulario.
     */
    private void cargarDatosProducto() {
        ProductoDTO producto = control.obtenerProductoParaEdicion(idProductoActual, this);

        if (producto != null) {
            txtNombre.setText(producto.getNombre());
            txtaDescripcion.setText(producto.getDescripcion());
            txtPrecioVenta.setText(String.valueOf(producto.getPrecio()));
            cbxTipo.setSelectedItem(producto.getTipo().toString());
            cbxEstado.setSelectedItem(producto.getEstado().toString());
            imagenBytes = producto.getImagen();

            if (imagenBytes != null) {
                ImageIcon icono = new ImageIcon(imagenBytes);
                int width = lblImagen.getWidth() > 0 ? lblImagen.getWidth() : 130;
                int height = lblImagen.getHeight() > 0 ? lblImagen.getHeight() : 130;
                Image imagenEscalada = icono.getImage().getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(imagenEscalada));
                lblImagen.setText("");
            }

            modeloTabla.setRowCount(0);

            List<Object[]> filasIngredientes = control.obtenerFilasIngredientesTabla(producto.getDetallesReceta(), this);
            for (Object[] fila : filasIngredientes) {
                modeloTabla.addRow(fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlBanner = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        lblDatosGenerales = new javax.swing.JLabel();
        lblModificarProductos = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripcion = new javax.swing.JTextArea();
        lblPrecioVenta = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        btnSeleccionarImagen = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblReceta = new javax.swing.JLabel();
        lblIngredienteencontrado = new javax.swing.JLabel();
        btnBuscarIngrediente = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarIngrediente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnActualizarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(253, 244, 227));

        pnlBanner.setBackground(new java.awt.Color(254, 178, 26));

        btnRegresar.setBackground(new java.awt.Color(237, 63, 39));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout pnlBannerLayout = new javax.swing.GroupLayout(pnlBanner);
        pnlBanner.setLayout(pnlBannerLayout);
        pnlBannerLayout.setHorizontalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBannerLayout.setVerticalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnRegresar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblDatosGenerales.setBackground(new java.awt.Color(19, 70, 134));
        lblDatosGenerales.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblDatosGenerales.setForeground(new java.awt.Color(19, 70, 134));
        lblDatosGenerales.setText("Datos generales:");

        lblModificarProductos.setBackground(new java.awt.Color(19, 70, 134));
        lblModificarProductos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblModificarProductos.setForeground(new java.awt.Color(19, 70, 134));
        lblModificarProductos.setText("Modificar producto");

        lblNombre.setBackground(new java.awt.Color(19, 70, 134));
        lblNombre.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(19, 70, 134));
        lblNombre.setText("Nombre:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        lblDescripcion.setBackground(new java.awt.Color(19, 70, 134));
        lblDescripcion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(19, 70, 134));
        lblDescripcion.setText("Descripción del producto:");

        txtaDescripcion.setColumns(20);
        txtaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtaDescripcion);

        lblPrecioVenta.setBackground(new java.awt.Color(19, 70, 134));
        lblPrecioVenta.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblPrecioVenta.setForeground(new java.awt.Color(19, 70, 134));
        lblPrecioVenta.setText("Precio de venta $:");

        txtPrecioVenta.addActionListener(this::txtPrecioVentaActionPerformed);

        lblTipo.setBackground(new java.awt.Color(19, 70, 134));
        lblTipo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(19, 70, 134));
        lblTipo.setText("Tipo:");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLATILLO", "BEBIDA", "POSTRE", "EXTRA", " " }));

        lblEstado.setBackground(new java.awt.Color(19, 70, 134));
        lblEstado.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(19, 70, 134));
        lblEstado.setText("Estado:");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO", " " }));

        btnSeleccionarImagen.setText("Seleccionar imagen");
        btnSeleccionarImagen.addActionListener(this::btnSeleccionarImagenActionPerformed);

        lblImagen.setText("jLabel1");

        lblReceta.setBackground(new java.awt.Color(19, 70, 134));
        lblReceta.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblReceta.setForeground(new java.awt.Color(19, 70, 134));
        lblReceta.setText("Receta:");

        lblIngredienteencontrado.setBackground(new java.awt.Color(19, 70, 134));
        lblIngredienteencontrado.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblIngredienteencontrado.setForeground(new java.awt.Color(19, 70, 134));
        lblIngredienteencontrado.setText("Ingrediente");

        btnBuscarIngrediente.setBackground(new java.awt.Color(19, 70, 134));
        btnBuscarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarIngrediente.setText("Buscar ingrediente");
        btnBuscarIngrediente.addActionListener(this::btnBuscarIngredienteActionPerformed);

        lblCantidad.setBackground(new java.awt.Color(19, 70, 134));
        lblCantidad.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(19, 70, 134));
        lblCantidad.setText("Cantidad:");

        txtCantidad.setText("jTextField1");

        btnAgregarIngrediente.setBackground(new java.awt.Color(254, 178, 26));
        btnAgregarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarIngrediente.setText("Agregar Ingredeinte");
        btnAgregarIngrediente.addActionListener(this::btnAgregarIngredienteActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id ", "Nombre", "Cantidad Requerida", "Unidad de medida", "Acciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnActualizarProducto.setBackground(new java.awt.Color(19, 70, 134));
        btnActualizarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarProducto.setText("Actualizar producto");
        btnActualizarProducto.addActionListener(this::btnActualizarProductoActionPerformed);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatosGenerales)
                            .addComponent(lblReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                                    .addComponent(lblIngredienteencontrado)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCantidad)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgregarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre)
                                    .addComponent(btnSeleccionarImagen)
                                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescripcion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPrecioVenta)
                                            .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTipo)
                                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(btnActualizarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPrincipalLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lblModificarProductos)
                    .addContainerGap(488, Short.MAX_VALUE)))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(lblDatosGenerales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblDescripcion)
                    .addComponent(lblPrecioVenta)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEstado)
                                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionarImagen))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReceta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngredienteencontrado)
                    .addComponent(btnBuscarIngrediente)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarIngrediente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarProducto)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPrincipalLayout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(lblModificarProductos)
                    .addContainerGap(548, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filtro);
        fileChooser.setAcceptAllFileFilterUsed(false);

        if (fileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            try {
                java.io.File archivo = fileChooser.getSelectedFile();
                imagenBytes = Files.readAllBytes(archivo.toPath());

                ImageIcon icono = new ImageIcon(imagenBytes);
                Image imagenEscalada = icono.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);

                lblImagen.setIcon(new ImageIcon(imagenEscalada));
                lblImagen.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    private void btnBuscarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIngredienteActionPerformed
        BuscadorInventarioJDialog buscador = new BuscadorInventarioJDialog(this, true, null);
        ingredienteSeleccionado = buscador.getIngredienteSeleccionado();
        if (ingredienteSeleccionado != null) {
            lblIngredienteencontrado.setText(ingredienteSeleccionado.getNombre() + " (" + ingredienteSeleccionado.getUnidadMedida() + ")");
        }
    }//GEN-LAST:event_btnBuscarIngredienteActionPerformed

    private void btnAgregarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIngredienteActionPerformed
        if (ingredienteSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Primero busca y selecciona un ingrediente.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String cantidadStr = txtCantidad.getText().trim();
        if (cantidadStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa la cantidad requerida.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            float cantidad = Float.parseFloat(cantidadStr);
            if (cantidad <= 0) {
                throw new NumberFormatException();
            }

            boolean ingredienteExiste = false;

            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                Long idExistente = (Long) modeloTabla.getValueAt(i, 0);
                
                if (idExistente.equals(ingredienteSeleccionado.getIdIngrediente())) {
                    modeloTabla.setValueAt(cantidad, i, 2);
                    ingredienteExiste = true;
                    break;
                }
            }

            if (!ingredienteExiste) {
                modeloTabla.addRow(new Object[]{
                    ingredienteSeleccionado.getIdIngrediente(),
                    ingredienteSeleccionado.getNombre(),
                    cantidad,
                    ingredienteSeleccionado.getUnidadMedida(),
                    "Borrar"
                });
            }
            
            ingredienteSeleccionado = null;
            lblIngredienteencontrado.setText("Ningún ingrediente seleccionado");
            txtCantidad.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarIngredienteActionPerformed

    private void btnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductoActionPerformed
        String nombre = txtNombre.getText().trim();
        String descripcion = txtaDescripcion.getText().trim();
        String precioStr = txtPrecioVenta.getText().trim();
        String tipoStr = cbxTipo.getSelectedItem() != null ? cbxTipo.getSelectedItem().toString() : "";
        String estadoStr = cbxEstado.getSelectedItem() != null ? cbxEstado.getSelectedItem().toString() : "";

        List<Object[]> ingredientes = new ArrayList<>();
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            Long idIngrediente = (Long) modeloTabla.getValueAt(i, 0);
            String cantidad = modeloTabla.getValueAt(i, 2).toString();
            ingredientes.add(new Object[]{idIngrediente, cantidad});
        }

        control.guardarActualizacionProducto(idProductoActual, nombre, descripcion, precioStr, tipoStr, estadoStr, imagenBytes, ingredientes, this);
    }//GEN-LAST:event_btnActualizarProductoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ProductosFORM productosForm = new ProductosFORM();
        productosForm.setLocationRelativeTo(null);
        productosForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnAgregarIngrediente;
    private javax.swing.JButton btnBuscarIngrediente;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDatosGenerales;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblIngredienteencontrado;
    private javax.swing.JLabel lblModificarProductos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioVenta;
    private javax.swing.JLabel lblReceta;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlBanner;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextArea txtaDescripcion;
    // End of variables declaration//GEN-END:variables
}
