/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package itson.restaurantepresentacion;

import itson.restaurantedtos.ClienteFrecuenteDTO;
import itson.restaurantenegocio.ClientesFrecuentesBO;
import itson.restaurantenegocio.NegocioException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;

/**
 *
 * @author nafbr
 */
public class BuscadorClientesJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(BuscadorClientesJDialog.class.getName());
    private ClientesFrecuentesBO clientesBO;
    private DefaultListModel<String> modeloLista;
    private JPopupMenu popmCoincidencias;
    private javax.swing.JList<String> listCoincidencias;
    private List<ClienteFrecuenteDTO> encontrados;
    private ClienteFrecuenteDTO clienteSeleccionado = null;

    /**
     * Creates new form BuscadorClientesJDialog
     */
    public BuscadorClientesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        clientesBO = new ClientesFrecuentesBO();
        popmCoincidencias = new JPopupMenu();
        modeloLista = new DefaultListModel<>();
        listCoincidencias = new javax.swing.JList<>(modeloLista);
        JScrollPane scrllpLista = new JScrollPane(listCoincidencias);
        popmCoincidencias.add(scrllpLista);
        txtClienteBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String textoBusqueda = txtClienteBuscar.getText().trim();
                int keyCode = evt.getKeyCode();
                if (keyCode == java.awt.event.KeyEvent.VK_UP || keyCode == java.awt.event.KeyEvent.VK_DOWN) {
                    return;
                }
                if (textoBusqueda.length() >= 3) {
                    try {
                        modeloLista.clear();
                        encontrados = clientesBO.buscarClientes(textoBusqueda);

                        if (encontrados.isEmpty()) {
                            modeloLista.addElement("¡No se encuentra registrado el cliente!");
                        } else {
                            for (ClienteFrecuenteDTO c : encontrados) {
                                modeloLista.addElement(c.getNombre() + " " + c.getApellidoP());
                            }
                        }

                        int altura = listCoincidencias.getPreferredSize().height + 10;
                        int alturaFinal = Math.min(100, altura);

                        popmCoincidencias.setPopupSize(txtClienteBuscar.getWidth(), alturaFinal);
                        popmCoincidencias.show(txtClienteBuscar, 0, txtClienteBuscar.getHeight());
                        txtClienteBuscar.requestFocus();
                    } catch (NegocioException ex) {
                        System.out.println("Error en la búsqueda: " + ex.getMessage());
                    }
                } else {
                    popmCoincidencias.setVisible(false);
                }
            }
        });
        
        listCoincidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int index = listCoincidencias.locationToIndex(evt.getPoint());
                if (index >= 0 && encontrados != null && !encontrados.isEmpty()) {
                    clienteSeleccionado = encontrados.get(index);
                    dispose(); 
                }
            }
        });       
    }
    
    /**
     * Método que regresa el cliente seleccionado de la lista que se desplegó.
     * 
     * @return 
     */
    public ClienteFrecuenteDTO getClienteSeleccionado() {
        return clienteSeleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        lblLupaImg = new javax.swing.JLabel();
        txtClienteBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(188, 196, 201));
        panel1.setLayout(new java.awt.BorderLayout());

        lblLupaImg.setText("jLabel1");
        panel1.add(lblLupaImg, java.awt.BorderLayout.WEST);

        txtClienteBuscar.setBackground(new java.awt.Color(188, 196, 201));
        txtClienteBuscar.addActionListener(this::txtClienteBuscarActionPerformed);
        panel1.add(txtClienteBuscar, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Buscar cliente:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnCancelar)))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(57, 57, 57))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteBuscarActionPerformed
        if (txtClienteBuscar.getText().trim().isEmpty()) {
            clienteSeleccionado = null; // Nos aseguramos de que sea null
            this.dispose(); // Cerramos la ventana
        }
    }//GEN-LAST:event_txtClienteBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        clienteSeleccionado = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLupaImg;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtClienteBuscar;
    // End of variables declaration//GEN-END:variables
}
