/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Panel.java to edit this template
 */
package itson.restaurantepresentacion;

import itson.restaurantedtos.ClienteFrecuenteDTO;
import itson.restaurantenegocio.ClientesFrecuentesBO;
import itson.restaurantenegocio.NegocioException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Esta clase es reutilizable, se puede usar en comandas nuevamente ya que busca a los clientes.
 * 
 * @author Andrea Lara, Nahomi Figueroa, Zaira Barajas
 */
public class BuscadorClientesPanelFORM extends java.awt.Panel {

    private ClientesFrecuentesBO clientesBO;
    private DefaultListModel<String> modeloLista;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientesFrecuentesFORM.class.getName());

    /**
     * Creates new form BuscadorClientesPanel
     */
    public BuscadorClientesPanelFORM() {
        initComponents();
        popmCoincidencias.add(scrllpListaCoincidencias);
        clientesBO = new ClientesFrecuentesBO();
        modeloLista = new DefaultListModel<>();

        listCoincidencias.setModel(modeloLista);

        txtClienteBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String textoBusqueda = txtClienteBuscar.getText().trim();

                //Esto es para ignorar las flechas jeje
                int keyCode = evt.getKeyCode();
                if (keyCode == java.awt.event.KeyEvent.VK_UP || keyCode == java.awt.event.KeyEvent.VK_DOWN) {
                    return;
                }

                if (textoBusqueda.length() >= 3) {
                    try {
                        modeloLista.clear();
                        List<ClienteFrecuenteDTO> encontrados = clientesBO.buscarClientes(textoBusqueda);
                        if (encontrados.isEmpty()) {
                            modeloLista.addElement("¡Ningún cliente cumple con la busqueda!");
                        } else {
                            for (ClienteFrecuenteDTO c : encontrados) {
                                modeloLista.addElement(c.getNombre() + " " + c.getApellidoP());
                            }
                        }
                        int alturaIdeal = listCoincidencias.getPreferredSize().height + 10; 
                        int alturaFinal = Math.min(100, alturaIdeal);
                        //Se le pone un tamaño adecuado
                        popmCoincidencias.setPopupSize(txtClienteBuscar.getWidth(), alturaFinal);
                        popmCoincidencias.show(txtClienteBuscar, 0, txtClienteBuscar.getHeight());
                        txtClienteBuscar.requestFocus();
                    } catch (NegocioException ex) {
                        logger.severe("Error al cargar la tabla: " + ex.getMessage());
                    }
                } else {
                    popmCoincidencias.setVisible(false);
                }
            }
        });
    }

    public String getTextoBusqueda() {
        return txtClienteBuscar.getText().trim();
    }

    public void addBuscadorKeyListener(java.awt.event.KeyListener listener) {
        txtClienteBuscar.addKeyListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popmCoincidencias = new javax.swing.JPopupMenu();
        scrllpListaCoincidencias = new javax.swing.JScrollPane();
        listCoincidencias = new javax.swing.JList<>();
        lblLupaImg = new javax.swing.JLabel();
        txtClienteBuscar = new javax.swing.JTextField();

        listCoincidencias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrllpListaCoincidencias.setViewportView(listCoincidencias);

        setBackground(new java.awt.Color(188, 196, 201));
        setLayout(new java.awt.BorderLayout());

        lblLupaImg.setText("jLabel1");
        add(lblLupaImg, java.awt.BorderLayout.WEST);

        txtClienteBuscar.setBackground(new java.awt.Color(188, 196, 201));
        txtClienteBuscar.addActionListener(this::txtClienteBuscarActionPerformed);
        add(txtClienteBuscar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLupaImg;
    private javax.swing.JList<String> listCoincidencias;
    private javax.swing.JPopupMenu popmCoincidencias;
    private javax.swing.JScrollPane scrllpListaCoincidencias;
    private javax.swing.JTextField txtClienteBuscar;
    // End of variables declaration//GEN-END:variables
}
