/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package itson.restaurantepresentacion;

import itson.restaurantedtos.ProductoDTO;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;

/**
 *
 * @author nafbr
 */
public class BuscadorProductosJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(BuscadorProductosJDialog.class.getName());
    private ProductosControl control;
    private DefaultListModel<String> modeloLista;
    private JPopupMenu popmCoincidencias;
    private javax.swing.JList<String> listCoincidencias;
    private List<ProductoDTO> encontrados;
    private ProductoDTO productoSeleccionado = null;

    /**
     * Creates new form BuscadorProductosJDialog
     */
    public BuscadorProductosJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);

        control = new ProductosControl();
        popmCoincidencias = new JPopupMenu();
        modeloLista = new DefaultListModel<>();
        listCoincidencias = new javax.swing.JList<>(modeloLista);
        listCoincidencias.setFixedCellHeight(30);
        listCoincidencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        JScrollPane scrllpLista = new JScrollPane(listCoincidencias);
        scrllpLista.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        popmCoincidencias.add(scrllpLista);
        txtProductoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String textoBusqueda = txtProductoBuscar.getText().trim();
                int keyCode = evt.getKeyCode();

                if (keyCode == java.awt.event.KeyEvent.VK_UP || keyCode == java.awt.event.KeyEvent.VK_DOWN) {
                    return;
                }

                if (textoBusqueda.length() >= 3) {
                    try {
                        modeloLista.clear();

                        encontrados = control.buscarPorNombreActivos(textoBusqueda);

                        if (encontrados.isEmpty()) {
                            modeloLista.addElement("¡No se encuentra registrado el producto!");
                        } else {
                            for (ProductoDTO p : encontrados) {
                                modeloLista.addElement(p.getNombre() + " - $" + String.format("%.2f", p.getPrecio()));
                            }
                        }
                        int altura = listCoincidencias.getPreferredSize().height + 10;
                        int alturaFinal = Math.min(250, Math.max(50, altura)); 

                        int ancho = Math.max(txtProductoBuscar.getWidth(), 250);

                        popmCoincidencias.setPopupSize(ancho, alturaFinal);
                        popmCoincidencias.show(txtProductoBuscar, 0, txtProductoBuscar.getHeight());
                        txtProductoBuscar.requestFocus();
                    } catch (Exception ex) {
                        LOGGER.warning("Error en la búsqueda de productos: " + ex.getMessage());
                    }
                } else {
                    popmCoincidencias.setVisible(false);
                }
            }
        });

        listCoincidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int index = listCoincidencias.locationToIndex(evt.getPoint());
                if (index >= 0 && encontrados != null && !encontrados.isEmpty()) {
                    if (encontrados.size() > index) {
                        productoSeleccionado = encontrados.get(index);
                        dispose();
                    }
                }
            }
        });
    }

    /**
     * Método que regresa el producto seleccionado de la lista que se desplegó.
     *
     * * @return ProductoDTO seleccionado o null si se canceló.
     */
    public ProductoDTO getProductoSeleccionado() {
        return productoSeleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        lblLupaImg = new javax.swing.JLabel();
        txtProductoBuscar = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscador de productos");

        jPanel1.setBackground(new java.awt.Color(19, 70, 134));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar un producto:");

        panel1.setBackground(new java.awt.Color(188, 196, 201));
        panel1.setLayout(new java.awt.BorderLayout());

        lblLupaImg.setText("jLabel1");
        panel1.add(lblLupaImg, java.awt.BorderLayout.WEST);

        txtProductoBuscar.setBackground(new java.awt.Color(188, 196, 201));
        txtProductoBuscar.addActionListener(this::txtProductoBuscarActionPerformed);
        panel1.add(txtProductoBuscar, java.awt.BorderLayout.CENTER);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnCancelar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnCancelar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoBuscarActionPerformed
        if (txtProductoBuscar.getText().trim().isEmpty()) {
            txtProductoBuscar = null; // Nos aseguramos de que sea null
            this.dispose(); // Cerramos la ventana
        }
    }//GEN-LAST:event_txtProductoBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        productoSeleccionado = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLupaImg;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtProductoBuscar;
    // End of variables declaration//GEN-END:variables
}
