/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.restaurantepresentacion;

import itson.restaurantedtos.ClienteFrecuenteDTO;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Andrea Lara, Nahomi Figueroa, Zaira Barajas
 */
public class ClientesFrecuentesFORM extends javax.swing.JFrame {

    private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(ClientesFrecuentesFORM.class.getName());
    private ClientesFrecuentesControl control;
    
    /**
     * Creates new form ClientesFrecuentesFORM
     */
    public ClientesFrecuentesFORM() {
        initComponents();
        jTable1.getColumnModel().getColumn(5).setCellRenderer(new BotonRenderer());
        jTable1.setRowHeight(30);
    }

    public void setControl(ClientesFrecuentesControl control) {
        this.control = control;
    }
    
    public javax.swing.JButton getBtnAñadirCliente() {
        return btnAnadirCliente;
    }

    public javax.swing.JTable getTablaClientes() {
        return jTable1;
    }

    public JButton getBtnInventario() {
        return btnInventario;
    }

    public JButton getBtnPlatillos() {
        return btnPlatillos;
    }

    public JButton getBtnReporteClientes() {
        return btnReporteClientes;
    }

    public JButton getBtnReporteComandas() {
        return btnReporteComandas;
    }

    public JButton getBtnMenu() {
        return btnMenu;
    }
    
    class BotonRenderer extends javax.swing.JButton implements javax.swing.table.TableCellRenderer {
        public BotonRenderer() {
            setOpaque(true);
            setBackground(new java.awt.Color(254, 178, 26));
            setForeground(java.awt.Color.WHITE);
            setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        }

        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if (value == null) {
                this.setText("Modificar");
            } else {
                this.setText(value.toString());
            }
            return this;
        }
    }

    public static class BotonModificar extends javax.swing.DefaultCellEditor {

        protected javax.swing.JButton button;
        private String label;
        private boolean isPushed;
        private int currentRow;
        private javax.swing.JTable tabla;
        private ClientesFrecuentesControl control;

        public BotonModificar(javax.swing.JCheckBox checkBox, javax.swing.JTable tabla, ClientesFrecuentesControl control) {
            super(checkBox);
            this.tabla = tabla;
            button = new javax.swing.JButton();
            button.setOpaque(true);
            button.setBackground(new java.awt.Color(254, 178, 26));
            button.setForeground(java.awt.Color.WHITE);
            button.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    fireEditingStopped();
                }
            });
            this.control = control;
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            this.currentRow = row;
            this.label = (value == null) ? "Editar" : value.toString();
            button.setText(label);
            isPushed = true;
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            if (isPushed) {
                // Solo se marca que se pulsó el botón en la fila actual
                // El controlador usará currentRow para hacer la lógica
                control.actualizar(currentRow);

            }
            isPushed = false;
            return label;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }

    }

    private void btnAnadirClienteActionPerformed(java.awt.event.ActionEvent evt) {  
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlClientesFrecuentes = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnInventario = new javax.swing.JButton();
        btnPlatillos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnReporteComandas = new javax.swing.JButton();
        btnReporteClientes = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblClientes = new javax.swing.JLabel();
        pnlBuscador = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAnadirCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes Frecuentes");
        setBackground(new java.awt.Color(253, 244, 227));

        pnlClientesFrecuentes.setBackground(new java.awt.Color(253, 244, 227));

        pnlMenu.setBackground(new java.awt.Color(19, 70, 134));

        btnInventario.setBackground(new java.awt.Color(19, 70, 134));
        btnInventario.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(253, 244, 227));
        btnInventario.setText("Inventario");
        btnInventario.setBorder(null);
        btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnPlatillos.setBackground(new java.awt.Color(19, 70, 134));
        btnPlatillos.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnPlatillos.setForeground(new java.awt.Color(253, 244, 227));
        btnPlatillos.setText("Gestionar platillos");
        btnPlatillos.setBorder(null);
        btnPlatillos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnClientes.setBackground(new java.awt.Color(254, 178, 26));
        btnClientes.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(253, 244, 227));
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnReportes.setBackground(new java.awt.Color(19, 70, 134));
        btnReportes.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(253, 244, 227));
        btnReportes.setText("Reportes");
        btnReportes.setToolTipText("");
        btnReportes.setBorder(null);
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnReporteComandas.setBackground(new java.awt.Color(19, 70, 134));
        btnReporteComandas.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnReporteComandas.setForeground(new java.awt.Color(253, 244, 227));
        btnReporteComandas.setText("Reportes de comandas");
        btnReporteComandas.setToolTipText("");
        btnReporteComandas.setBorder(null);
        btnReporteComandas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReporteComandas.addActionListener(this::btnReporteComandasActionPerformed);

        btnReporteClientes.setBackground(new java.awt.Color(19, 70, 134));
        btnReporteClientes.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnReporteClientes.setForeground(new java.awt.Color(253, 244, 227));
        btnReporteClientes.setText("Reportes de clientes");
        btnReporteClientes.setToolTipText("");
        btnReporteClientes.setBorder(null);
        btnReporteClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReporteClientes.addActionListener(this::btnReporteClientesActionPerformed);

        btnMenu.setBackground(new java.awt.Color(19, 70, 134));
        btnMenu.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(253, 244, 227));
        btnMenu.setText("Menú Principal");
        btnMenu.setBorder(null);
        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPlatillos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporteComandas)
                    .addComponent(btnReporteClientes))
                .addGap(20, 20, 20))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteComandas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReporteClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblClientes.setBackground(new java.awt.Color(19, 70, 134));
        lblClientes.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(19, 70, 134));
        lblClientes.setText("Clientes");

        pnlBuscador.setLayout(new java.awt.BorderLayout());

        lblBuscar.setFont(new java.awt.Font("Segoe UI Emoji", 2, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(19, 70, 134));
        lblBuscar.setText("Buscar clientes por su nombre, número de teléfono o correo:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre completo", "Teléfono", "Puntos", "Total Gastado ", "Acción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        btnAnadirCliente.setBackground(new java.awt.Color(19, 70, 134));
        btnAnadirCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAnadirCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirCliente.setText("Añadir Cliente");
        btnAnadirCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnadirCliente.addActionListener(this::btnAnadirClienteActionPerformed);

        btnBuscarCliente.setBackground(new java.awt.Color(254, 178, 26));
        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("Buscar cliente");
        btnBuscarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarCliente.addActionListener(this::btnBuscarClienteActionPerformed);

        javax.swing.GroupLayout pnlClientesFrecuentesLayout = new javax.swing.GroupLayout(pnlClientesFrecuentes);
        pnlClientesFrecuentes.setLayout(pnlClientesFrecuentesLayout);
        pnlClientesFrecuentesLayout.setHorizontalGroup(
            pnlClientesFrecuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesFrecuentesLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlClientesFrecuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesFrecuentesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlClientesFrecuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlClientesFrecuentesLayout.createSequentialGroup()
                                .addGap(511, 511, 511)
                                .addComponent(pnlBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlClientesFrecuentesLayout.createSequentialGroup()
                                .addGroup(pnlClientesFrecuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(176, 176, 176)
                                .addComponent(btnAnadirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlClientesFrecuentesLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClientesFrecuentesLayout.setVerticalGroup(
            pnlClientesFrecuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlClientesFrecuentesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblClientes)
                .addGap(20, 20, 20)
                .addComponent(pnlBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientesFrecuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnadirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlClientesFrecuentes, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlClientesFrecuentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteComandasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteComandasActionPerformed

    private void btnReporteClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteClientesActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        BuscadorClientesJDialog buscador = new BuscadorClientesJDialog(this, true);
        buscador.setVisible(true);
        ClienteFrecuenteDTO cliente = buscador.getClienteSeleccionado();
        
        if (cliente != null) {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0); 
            String apellidoM = (cliente.getApellidoM() != null) ? " " + cliente.getApellidoM() : "";
            String nombreCompleto = cliente.getNombre() + " " + cliente.getApellidoP() + apellidoM;
            modelo.addRow(new Object[]{
                cliente.getId(),
                nombreCompleto,
                cliente.getNumeroTelefono(), 
                cliente.getPuntos(),
                "0.0", //Ya que exista el metodo le movemos
                "Modificar"
            });
        } else {
            if (this.control != null) {
                this.control.cargarTabla(""); 
            }
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPlatillos;
    private javax.swing.JButton btnReporteClientes;
    private javax.swing.JButton btnReporteComandas;
    private javax.swing.JButton btnReportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JPanel pnlBuscador;
    private javax.swing.JPanel pnlClientesFrecuentes;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
