/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.restaurantepresentacion;

import itson.restaurantedominio.ClienteFrecuente;
import itson.restaurantedtos.ClienteFrecuenteNuevoDTO;
import itson.restaurantenegocio.ClientesFrecuentesBO;
import itson.restaurantenegocio.IClientesFrecuentesBO;
import itson.restaurantenegocio.NegocioException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Forma de registro de clientes
 *
 * @author Andrea Lara, Nahomi Figueroa, Zaira Barajas
 */
public class RegistroClientesFORM extends javax.swing.JFrame {

    private IClientesFrecuentesBO clientesBO;

    /**
     * Creates new form RegistroClientes
     */
    public RegistroClientesFORM() {
        initComponents();
        this.clientesBO = new ClientesFrecuentesBO();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlFormulario = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblObligatorio = new javax.swing.JLabel();
        lblCorreo1 = new javax.swing.JLabel();
        lblEjemplo1 = new javax.swing.JLabel();
        lblEjemploTelefono1 = new javax.swing.JLabel();
        lblEjemplo2 = new javax.swing.JLabel();
        lblEjemploCorreo = new javax.swing.JLabel();
        lblEjemploTelefono2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resgistro de cliente");

        pnlPrincipal.setBackground(new java.awt.Color(253, 244, 227));

        pnlFormulario.setBackground(new java.awt.Color(254, 178, 26));
        pnlFormulario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNombre.setBackground(new java.awt.Color(254, 178, 26));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(19, 70, 134));
        lblNombre.setText("Nombre(s):");

        lblApellidoP.setBackground(new java.awt.Color(254, 178, 26));
        lblApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblApellidoP.setForeground(new java.awt.Color(19, 70, 134));
        lblApellidoP.setText("Apellido Paterno:");

        lblApellidoM.setBackground(new java.awt.Color(254, 178, 26));
        lblApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblApellidoM.setForeground(new java.awt.Color(19, 70, 134));
        lblApellidoM.setText("Apellido Materno:");

        lblTelefono.setBackground(new java.awt.Color(254, 178, 26));
        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(19, 70, 134));
        lblTelefono.setText("Teléfono:");

        lblObligatorio.setBackground(new java.awt.Color(254, 178, 26));
        lblObligatorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblObligatorio.setForeground(new java.awt.Color(19, 70, 134));
        lblObligatorio.setText("(*) Opcional");

        lblCorreo1.setBackground(new java.awt.Color(254, 178, 26));
        lblCorreo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(19, 70, 134));
        lblCorreo1.setText("Correo*:");

        lblEjemplo1.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemplo1.setText("Ejemplo:");

        lblEjemploTelefono1.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemploTelefono1.setText("6441-12-12-12");

        lblEjemplo2.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemplo2.setText("Ejemplo:");

        lblEjemploCorreo.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemploCorreo.setText("micorreo@dominio.com");

        lblEjemploTelefono2.setForeground(new java.awt.Color(19, 70, 134));
        lblEjemploTelefono2.setText("(+52)6442-67-67-67");

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEjemplo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEjemploTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEjemploTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEjemploCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEjemplo2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFormularioLayout.createSequentialGroup()
                                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(lblCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblApellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblApellidoM)
                                    .addComponent(lblObligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19))))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidoP)
                    .addComponent(lblApellidoM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblTelefono))
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblObligatorio)
                            .addComponent(lblCorreo1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblEjemplo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEjemploCorreo))
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEjemplo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEjemploTelefono1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEjemploTelefono2)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnRegistrar.setBackground(new java.awt.Color(19, 70, 134));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(237, 63, 39));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(19, 70, 134));
        lblTitulo.setText("Registro de Clientes Frecuentes");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(lblTitulo))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btnRegresar)
                        .addGap(130, 130, 130)
                        .addComponent(btnRegistrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(27, 27, 27)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnRegistrar))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este botón cierra la forma de registro de clientes.
     *
     * @param evt click al botón regresar.
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ClientesFrecuentesControl.abrirClientesFrecuentes(this);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * Botón que llama al método registrarCliente(), en caso de un registro
     * éxitoso lanza un mensaje y cierra la ventana. En caso contrario, muestra
     * mensajes de error.
     *
     * @param evt click al botón registrar.
     */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        ClienteFrecuente cF = registrarCliente();
        if (cF != null) {
            JOptionPane.showMessageDialog(null, "¡Cliente agregado con éxito!");
            ClientesFrecuentesControl.abrirClientesFrecuentes(this);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * Este método recupera y válida los datos de la forma para registrar con
     * ellos un nuevo cliente en la base de datos.
     *
     * @return un objeto tipo ClienteFrecuente con los datos del cliente
     * registrado.
     */
    public ClienteFrecuente registrarCliente() {
        String nombre = null;
        String apellidoP = null;
        String apellidoM = null;
        String telefono = null;
        String correo = null;

        if (!txtNombre.getText().trim().isBlank() || !txtNombre.getText().trim().isEmpty()) {
            nombre = txtNombre.getText();
        } else {
            JOptionPane.showMessageDialog(null, "El nombre es obligatorio ", "Campo obligatorio vacío", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (!txtApellidoP.getText().trim().isBlank() || !txtApellidoP.getText().trim().isEmpty()) {
            apellidoP = txtApellidoP.getText();
        } else {
            JOptionPane.showMessageDialog(null, "El apellido paterno es obligatorio ", "Campo obligatorio vacío", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (!txtApellidoM.getText().trim().isBlank() || !txtApellidoM.getText().trim().isEmpty()) {
            apellidoM = txtApellidoM.getText();
        } else {
            JOptionPane.showMessageDialog(null, "El apellido materno es obligatorio ", "Campo obligatorio vacío", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (!txtTelefono.getText().trim().isBlank() || !txtTelefono.getText().trim().isEmpty()) {
            telefono = txtTelefono.getText();
        } else {
            JOptionPane.showMessageDialog(null, "El teléfono es obligatorio ", "Campo obligatorio vacío", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (!txtCorreo.getText().trim().isBlank() || !txtCorreo.getText().trim().isEmpty()) {
            correo = txtCorreo.getText();
        }

        ClienteFrecuenteNuevoDTO clienteNuevo = new ClienteFrecuenteNuevoDTO(nombre, apellidoP, apellidoM, telefono, correo);

        try {
            ClienteFrecuente cliente = clientesBO.crearCliente(clienteNuevo);
            return cliente;
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar cliente" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblEjemplo1;
    private javax.swing.JLabel lblEjemplo2;
    private javax.swing.JLabel lblEjemploCorreo;
    private javax.swing.JLabel lblEjemploTelefono1;
    private javax.swing.JLabel lblEjemploTelefono2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObligatorio;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
