/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.restaurantepresentacion;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zaira
 */
public class ReporteComandasFORM extends javax.swing.JFrame {

    /**
     * Creates new form ReporteComandas
     */
    public ReporteComandasFORM() {
        initComponents();
    }

    public JButton getBtnGenerarPDF() {
        return btnGenerarPDF;
    }

    public JButton getBtnGenerarReporte() {
        return btnGenerarReporte;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JButton getBtnReporteClientes() {
        return btnReporteClientes;
    }

    public JLabel getLblVentaTotalCantidad() {
        return lblVentaTotalCantidad;
    }

    public JTable getTablaComandas() {
        return tablaComandas;
    }

    public JFormattedTextField getTxtFechaFin() {
        return txtFechaFin;
    }

    public JFormattedTextField getTxtFechaInicio() {
        return txtFechaInicio;
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReporteComandas = new javax.swing.JPanel();
        pnlEncabezado = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnReporteClientes = new javax.swing.JButton();
        scrollTablaComandas = new javax.swing.JScrollPane();
        tablaComandas = new javax.swing.JTable();
        btnGenerarPDF = new javax.swing.JButton();
        lblFechaFin = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblTituloReporteComandas = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JFormattedTextField();
        lblVentaTotalTitulo = new javax.swing.JLabel();
        lblVentaTotalCantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlReporteComandas.setBackground(new java.awt.Color(253, 244, 227));

        pnlEncabezado.setBackground(new java.awt.Color(254, 178, 26));

        btnRegresar.setBackground(new java.awt.Color(237, 63, 39));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");

        btnReporteClientes.setBackground(new java.awt.Color(188, 202, 220));
        btnReporteClientes.setForeground(new java.awt.Color(51, 51, 51));
        btnReporteClientes.setText("Reporte Clientes");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 515, Short.MAX_VALUE)
                .addComponent(btnReporteClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnReporteClientes))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        scrollTablaComandas.setBackground(new java.awt.Color(255, 255, 255));

        tablaComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTablaComandas.setViewportView(tablaComandas);

        btnGenerarPDF.setBackground(new java.awt.Color(255, 212, 125));
        btnGenerarPDF.setForeground(new java.awt.Color(51, 51, 51));
        btnGenerarPDF.setText("Generar PDF");

        lblFechaFin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaFin.setForeground(new java.awt.Color(19, 70, 134));
        lblFechaFin.setText("Fecha Fin:");

        btnGenerarReporte.setBackground(new java.awt.Color(188, 202, 220));
        btnGenerarReporte.setForeground(new java.awt.Color(51, 51, 51));
        btnGenerarReporte.setText("Generar Reporte");

        btnLimpiar.setBackground(new java.awt.Color(237, 63, 39));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");

        lblTituloReporteComandas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloReporteComandas.setForeground(new java.awt.Color(19, 70, 134));
        lblTituloReporteComandas.setText("Reporte de Comandas");

        txtFechaInicio.setBackground(new java.awt.Color(255, 255, 255));

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(19, 70, 134));
        lblFechaInicio.setText("Fecha Inicio:");

        txtFechaFin.setBackground(new java.awt.Color(255, 255, 255));

        lblVentaTotalTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVentaTotalTitulo.setForeground(new java.awt.Color(19, 70, 134));
        lblVentaTotalTitulo.setText("Venta Total:");

        lblVentaTotalCantidad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVentaTotalCantidad.setForeground(new java.awt.Color(19, 70, 134));

        javax.swing.GroupLayout pnlReporteComandasLayout = new javax.swing.GroupLayout(pnlReporteComandas);
        pnlReporteComandas.setLayout(pnlReporteComandasLayout);
        pnlReporteComandasLayout.setHorizontalGroup(
            pnlReporteComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteComandasLayout.createSequentialGroup()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReporteComandasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlReporteComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReporteComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReporteComandasLayout.createSequentialGroup()
                            .addComponent(lblVentaTotalTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblVentaTotalCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarPDF))
                        .addComponent(scrollTablaComandas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReporteComandasLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lblFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(lblFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarReporte)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimpiar)))
                    .addComponent(lblTituloReporteComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        pnlReporteComandasLayout.setVerticalGroup(
            pnlReporteComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteComandasLayout.createSequentialGroup()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloReporteComandas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReporteComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReporteComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGenerarReporte)
                        .addComponent(btnLimpiar)
                        .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReporteComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFechaFin)
                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaInicio)))
                .addGap(18, 18, 18)
                .addComponent(scrollTablaComandas, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlReporteComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarPDF)
                    .addComponent(lblVentaTotalTitulo)
                    .addComponent(lblVentaTotalCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReporteComandas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReporteComandas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReporteClientes;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblTituloReporteComandas;
    private javax.swing.JLabel lblVentaTotalCantidad;
    private javax.swing.JLabel lblVentaTotalTitulo;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlReporteComandas;
    private javax.swing.JScrollPane scrollTablaComandas;
    private javax.swing.JTable tablaComandas;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
